"""baseline

Revision ID: 988adbf12037
Revises: 
Create Date: 2026-06-24 22:39:28.721531+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988adbf12037'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('sous_reseau', sa.String(length=20), nullable=False),
    sa.Column('etage', sa.Enum('SOUS_SOL', 'RDC', 'ETAGE_1', 'ETAGE_2', name='etage'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'INFORMATICIEN', 'DEMANDEUR', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('postes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('salle', sa.String(length=50), nullable=False),
    sa.Column('utilisateur', sa.String(length=150), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postes_nom'), 'postes', ['nom'], unique=False)
    op.create_index(op.f('ix_postes_salle'), 'postes', ['salle'], unique=False)
    op.create_index(op.f('ix_postes_utilisateur'), 'postes', ['utilisateur'], unique=False)
    op.create_table('equipements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('n_serie', sa.String(length=100), nullable=True),
    sa.Column('code_barre', sa.String(length=100), nullable=True),
    sa.Column('inventaire', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('PC', 'ECRAN', 'IMPRIMANTE', 'SCANNER', 'SWITCH', 'ROUTEUR', 'ONDULEUR', 'TELEPHONE', 'SERVEUR', 'AUTRE', name='equipementtype'), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=150), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('poste_id', sa.UUID(), nullable=True),
    sa.Column('etat', sa.Enum('OPERATIONNEL', 'EN_PANNE', 'EN_MAINTENANCE', 'REFORME', name='equipementetat'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_equipements_code_barre'), 'equipements', ['code_barre'], unique=True)
    op.create_index(op.f('ix_equipements_inventaire'), 'equipements', ['inventaire'], unique=True)
    op.create_index(op.f('ix_equipements_n_serie'), 'equipements', ['n_serie'], unique=True)
    op.create_index(op.f('ix_equipements_poste_id'), 'equipements', ['poste_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('nature', sa.Enum('TECHNIQUE', 'METIER', 'ASSISTANCE', 'MAINTENANCE', name='ticketnature'), nullable=False),
    sa.Column('priorite', sa.Enum('URGENT', 'NORMAL', 'FAIBLE', name='ticketpriorite'), nullable=False),
    sa.Column('statut', sa.Enum('NOUVEAU', 'EN_COURS', 'RESOLU', 'CLOTURE', 'ANNULE', name='ticketstatut'), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('poste_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipement_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipement_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipement_history_equipement_id'), 'equipement_history', ['equipement_id'], unique=False)
    op.create_table('ticket_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_equipements',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('equipement_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'equipement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_equipements')
    op.drop_table('ticket_actions')
    op.drop_index(op.f('ix_equipement_history_equipement_id'), table_name='equipement_history')
    op.drop_table('equipement_history')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_equipements_poste_id'), table_name='equipements')
    op.drop_index(op.f('ix_equipements_n_serie'), table_name='equipements')
    op.drop_index(op.f('ix_equipements_inventaire'), table_name='equipements')
    op.drop_index(op.f('ix_equipements_code_barre'), table_name='equipements')
    op.drop_table('equipements')
    op.drop_index(op.f('ix_postes_utilisateur'), table_name='postes')
    op.drop_index(op.f('ix_postes_salle'), table_name='postes')
    op.drop_index(op.f('ix_postes_nom'), table_name='postes')
    op.drop_table('postes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('services')
    # ### end Alembic commands ###
