"""ticket numero and action kind

Two additions:

- ``tickets.numero``: a human-readable sequential ticket number, generated by
  the database as an IDENTITY column so concurrent inserts can't collide.
  Existing rows are backfilled in ``created_at`` order, so the numbering
  matches the order tickets were actually opened rather than row-storage
  order, and the identity generator then restarts past the highest value.

- ``ticket_actions.kind``: distinguishes typed comments from server-written
  audit entries (status transitions, assignment changes). Existing rows are
  all human comments, which is exactly the ``COMMENTAIRE`` default.

Both are additive and backfilled in place, so this is safe to run against the
deployed database with data in it.

Revision ID: d4a8c2b6e9f1
Revises: c3f7e1a9b8d2
Create Date: 2026-09-03 00:00:00+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4a8c2b6e9f1'
down_revision: Union[str, Sequence[str], None] = 'c3f7e1a9b8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# SQLAlchemy's Enum persists member NAMES, so the Postgres labels are
# uppercase — matching the convention used by the baseline migration.
ACTION_KIND_VALUES = ('COMMENTAIRE', 'STATUT', 'ASSIGNATION')

BACKFILL_NUMERO = """
    WITH ordered AS (
        SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn
        FROM tickets
    )
    UPDATE tickets t
    SET numero = ordered.rn
    FROM ordered
    WHERE t.id = ordered.id
"""

# Start the generator past the backfilled rows, otherwise the first insert
# after this migration collides with an existing number.
RESTART_IDENTITY = """
    SELECT setval(
        pg_get_serial_sequence('tickets', 'numero'),
        COALESCE((SELECT MAX(numero) FROM tickets), 0) + 1,
        false
    )
"""


def upgrade() -> None:
    # --- tickets.numero ---------------------------------------------------
    # Added nullable so existing rows survive the ALTER, then backfilled and
    # tightened to NOT NULL below.
    op.add_column('tickets', sa.Column('numero', sa.Integer(), nullable=True))
    op.execute(sa.text(BACKFILL_NUMERO))
    op.alter_column('tickets', 'numero', nullable=False)

    # BY DEFAULT (not ALWAYS) so a data import can still supply explicit
    # numbers. The identity's sequence is owned by the column, so it is
    # dropped along with it and never left stranded.
    op.execute(sa.text(
        "ALTER TABLE tickets ALTER COLUMN numero ADD GENERATED BY DEFAULT AS IDENTITY"
    ))
    op.execute(sa.text(RESTART_IDENTITY))

    op.create_index(op.f('ix_tickets_numero'), 'tickets', ['numero'], unique=True)

    # --- ticket_actions.kind ----------------------------------------------
    action_kind = sa.Enum(*ACTION_KIND_VALUES, name='ticketactionkind')
    action_kind.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'ticket_actions',
        sa.Column(
            'kind',
            action_kind,
            nullable=False,
            server_default='COMMENTAIRE',
        ),
    )


def downgrade() -> None:
    op.drop_column('ticket_actions', 'kind')
    sa.Enum(name='ticketactionkind').drop(op.get_bind(), checkfirst=True)

    op.drop_index(op.f('ix_tickets_numero'), table_name='tickets')
    # Dropping the column drops its identity sequence with it.
    op.drop_column('tickets', 'numero')
